### ISSUE TITLE
Update quickstart workflow failures

### ISSUE THREAD

**Issue by aswanson-nr** [newrelic/newrelic-quickstarts#881]
## Description
We are seeing some failures in the quickstart update workflow, this is an umbrella issue to track what we are seeing.

* Unable to submit a "New Relic" and "Verified" support level to EU
  * https://github.com/newrelic/newrelic-quickstarts/runs/5368282007?check_suite_focus=true
  * https://github.com/newrelic/newrelic-quickstarts/runs/5368282007?check_suite_focus=true
* Timed out submitting to staging
  * https://github.com/newrelic/newrelic-quickstarts/runs/5368386872?check_suite_focus=true 
  * https://github.com/newrelic/newrelic-quickstarts/runs/5368321417?check_suite_focus=true
  * https://github.com/newrelic/newrelic-quickstarts/runs/5336540875?check_suite_focus=true
  * https://github.com/newrelic/newrelic-quickstarts/runs/5336540875?check_suite_focus=true
* Time out while pulling down artifact with PR number
  * This is due to PRs being closed without merging, not a problem, but could be worth cleaning up. 
  * https://github.com/newrelic/newrelic-quickstarts/runs/5368267158?check_suite_focus=true

**Comment by jerelmiller** [comment]
@aswanson-nr make sure you're using an API key with NR admin privileges and that should fix the issue.

**Comment by aswanson-nr** [comment]
Updates:
* Admin privileges for the EU api key (in progress)
* Staging timeouts (investigation in progress)

Resolution plan:
1. Update EU API key
2. Rerun failed jobs to deploy changes to the catalog
3. If we're still seeing staging timeouts, refocus on this issue and then retry step 2

**Comment by aswanson-nr** [comment]
Update:
* EU API key has been fixed
* Workflows have been rerun
* Staging timeouts were not observed, so we will continue to keep an eye on that
* Merging PRs can now continue as normal

@nr-kkenney @jpvajda @zstix for visibility

**Comment by aswanson-nr** [comment]
Runbook has been updated with a link to the dashboard to track workflow events https://staging.onenr.io/0kLwGkzNew6
